# A cronjob for updating jasima

name: Cronjob for jasima

on:
  schedule:
    - cron: '0/5 * * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set up environment
      run: |
      env: 
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    - name: Install dependencies
      run: |
        cd update-job
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update jasima
      run: |
        cd update-job
        python jasima.py
